### ISSUE TITLE
Can you support putting the model locally without having to connect to huggingface every time?

### ISSUE THREAD

**Issue by suede299** [city96/SD-Latent-Upscaler#2]
It works great, but it's inconvenient to have to network to huggingface to find the model every time, and the model files aren't too big when I look at them, can't they just exist locally? My internet access is extremely low, it's clear that the process is fast, but waiting for the internet connection takes a long time.

**Comment by city96** [comment]
I feel you. My connection is also really flaky so I had it time out before when it wasn't using the cache.

Anyway, I added some simple logic to make it load the modules from disk if they're present. Instructions are in the readme on where to place them. You should see a message on the console when it executes (`LatentUpscaler: Using local model`).

**Comment by suede299** [comment]
> 我感觉到你了。我的连接也非常不稳定，所以我之前在不使用缓存时超时了。
> 
> 无论如何，我添加了一些简单的逻辑，使其从磁盘加载模块（如果存在）。自述文件中提供了有关放置它们的位置的说明。执行时，您应该会在控制台上看到一条消息 （）。`LatentUpscaler: Using local model`

Thank you so much for what you do.
Now there's no need for the Upscaler model to zoom in and then down to 2x size.

**Comment by city96** [comment]
No problem! I'll port the same change to my other repo tomorrow since it's easy enough to add.
