### ISSUE TITLE
upscaled latents look very wrong

### ISSUE THREAD

**Issue by brycedrennan** [city96/SD-Latent-Upscaler#4]
I'm sure I'm doing something wrong. I'm trying to integrate the latent upscaler into [imaginairy]() but the latents look like this after upscaling.  I'm using `latent-upscaler-v2.1_SDxl-x2.0.safetensors`. Input latent is `[1, 4, 128, 128]` 

Any ideas how I messed this up?  

![028936_1_ddim50_PS7 5_a_flower_ latent-upscaled](https://github.com/city96/SD-Latent-Upscaler/assets/1217531/c802bb62-7810-472a-ae8b-c824a3f65aa4)
original image:
![028936_1_ddim50_PS7 5_a_flower_ generated](https://github.com/city96/SD-Latent-Upscaler/assets/1217531/11e9585e-7e37-429f-bceb-c0259472aa0d)

**Comment by city96** [comment]
Are you scaling them before/after? It expects the values to be in the range the VAE outputs, so around `[-20;-20]` or so.

Try divide your latent by `0.18215` before passing it to the model and then multiply the output by the same value before passing it to the model. You could also be scaling it twice, i.e. ending up with massive values. (you might need to use `0.13025` for the multiplier with XL, depends on what your code uses)

**Comment by brycedrennan** [comment]
Thank's I'll investigate further

**Comment by brycedrennan** [comment]
Yes it was the scaling - that fixed it. thank you!
